name: WGDragonEggPortFlag
main: de.bangl.wgdepf.WGDragonEggPortFlagPlugin
description: WorldGuard extension to deny porting of dragon eggs in specific regions.
version: 0.3

authors: [ BangL ]
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]
