name: WGDragonEggPortFlag
version: 0.1
description: '"WorldGuard" extension to block porting of dragon eggs in specific regions.'
author: BangL
website: http://bangl.de/
depend: [WorldGuard, WGCustomFlags]
main: de.bangl.wgdepf.WGDragonEggPortFlagPlugin
