name: WGDragonEggPortFlag
version: 0.3
description: '"WorldGuard" extension to block porting of dragon eggs in specific regions.'
authors: [ BangL ]
depend: [ WorldGuard, WGCustomFlags ]
main: de.bangl.wgdepf.WGDragonEggPortFlagPlugin
